# Generated by Django 5.1.1 on 2024-10-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('GUARD', 'GUARD'), ('INSTRUCTOR', 'INSTRUCTOR'), ('ADMIN', 'ADMIN')], max_length=10),
        ),
    ]
