# Generated by Django 5.1.1 on 2024-10-20 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0002_alter_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program1', models.CharField(default='Default Program', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('violation_type', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major')], max_length=10)),
                ('description', models.TextField()),
                ('guidelines', models.TextField()),
                ('sanction_period_value', models.IntegerField()),
                ('sanction_period_type', models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmod.dropdownoption')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmod.course')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True, verbose_name='Middle Initial')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('idnumber', models.CharField(max_length=20, unique=True, verbose_name='ID Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=8, verbose_name='Password')),
                ('confirmpass', models.CharField(max_length=8, verbose_name='Confirm Password')),
                ('id_picture', models.FileField(upload_to='id_pictures/', verbose_name='ID Picture')),
                ('registration_cert', models.FileField(upload_to='registration_certs/', verbose_name='Registration Certificate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminmod.course')),
                ('program1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminmod.dropdownoption')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminmod.section')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmod.signup')),
                ('violation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmod.violationtype')),
            ],
        ),
    ]
