# Generated by Django 5.1.1 on 2024-11-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0003_dropdownoption_violationtype_course_section_signup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student_id', models.CharField(max_length=20)),
                ('violation', models.CharField(max_length=100)),
                ('violation_type', models.CharField(max_length=100)),
                ('reasons', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
